blank_issues_enabled: false
contact_links:
  - name: Questions about Butterfly
    url: https://github.com/anzhiyu-c/hexo-theme-anzhiyu/discussions
    about: 一些使用问题请到 Discussion 询问。 Please ask questions in Discussion.

  - name: AnZhiYu Q&A
    url: https://anzhiy.cn/comments/
    about: AnZhiYu Q&A
